### ISSUE TITLE
Making Fontraption resident

### ISSUE THREAD

**Issue by bleuge** [viler-int10h/fontraption#2]
Hi, today I was drawing some text interfaces in The Draw and I was thinking how nice would be to have Fontraption resident, load it, load some font and keep drawing, this can be used also in text editors, or other ANSI editors as AcidDraw, so you can load it and edit or load/save fonts whenever you like.
I know fonts can be activated from commandline, but having it resident all the time could be a nice feature.
Regards.

**Comment by viler-int10h** [comment]
That would probably be too big a rewrite, because right now it needs >200K of RAM to store things for the sake of speed (and probably assumes too much about the state of the VGA, too).
But, I should point out that Empathy for DOS is an ANSI editor which also has a font editor built in :)

**Comment by bleuge** [comment]
Ok, I was reading the source but have to get used to Fasm syntax :D
Code is so clean!

I'll check that editor, thanks. 
I am sure there are tools for loading fonts while staying resident, I'll check some DOS sites :D thanks!
