### ISSUE TITLE
Port to an easier assembler setup for better assembly!

### ISSUE THREAD

**Issue by TheRealHamtaro126** [viler-int10h/fontraption#3]
Hello, Love the Font editor you created, I may ask, Can you port it to a much better setup such as compiling on x64 (64bit) operating systems while maintaining DOS compatibility for generating executables, Flat Assembler G, or NASM alternatively, could do the job nicely.

Again, I appreciate the good work. Thank you.

**Comment by viler-int10h** [comment]
Can you clarify what issues you are having with FASM?  I have no problems building the DOS executable on my 64-bit system (Windows here, so mileage may vary).  Also, I've never used FASMG, but I expect it should be able to assemble FASM-syntax source for the same target,.. would be strange if it cannot.

Another reason for using FASM is that FASM for DOS works just as well.  So if you already have a DOS environment for the resulting executable, you can also run FASM there and build it from the same source.  Works fine for me in DOSBox/PCem/86box.
