### ISSUE TITLE
Please add a license to Fontraption

### ISSUE THREAD

**Issue by LinoMastro** [viler-int10h/fontraption#4]
Hi, could you please add a LICENSE.txt or similar file to Fontraption?

It would allow people (e.g. the FreeDOS distribution) to redistribute it.

Two popular licenses these days are MIT (https://choosealicense.com/licenses/mit/) or GPL (https://choosealicense.com/licenses/gpl-3.0/).

If you don't want to bother with a full license, could you please add a note in the README to the effect of "this software is released into the public domain".

Thanks!

**Comment by viler-int10h** [comment]
Shouldn't have taken me so long, but I've added the MIT license!
