### ISSUE TITLE
How to apply my new font to the whole system

### ISSUE THREAD

**Issue by peymanx** [viler-int10h/fontraption#7]
I made my own font with your charming app. but I don't know how to apply it to the system. 
is there any way to make an EXE file when I run it and apply the font?   
I made a Persian/Arabic font and I want to use it when I left [Fontraption]

**Comment by peymanx** [comment]
![image](https://user-images.githubusercontent.com/110537772/196860902-cb491fda-3ad9-4b83-a3cb-8ac6bef317bd.png)

**Comment by tomrow** [comment]
You can export a font by pressing Ctrl+E. Make sure to select .COM as the export format.

**Comment by peymanx** [comment]
I used FONTEDIT.COM and it's SETFONT feature... 
but great answer
Thanks for your response...

**Comment by viler-int10h** [comment]
@peymanx: closing thanks to **tomrow**'s answer, but it'd be cool if I could add your font to the [collection](https://github.com/viler-int10h/vga-text-mode-fonts) - let me know!
